site_name: Bitwyze Cloud Security
site_url: https://mnyethecyberguy.github.io/storm/
site_author: Michael Nye

# Repository
repo_name: mnyethecyberguy/storm
repo_url: https://github.com/mnyethecyberguy/storm

# Copyright
copyright: |
  &copy; 2024 <a href="https://mnye.io" target="_blank" rel="noopener">Michael Nye</a>

theme:
  name: material
  logo: assets/images/bitwyze-logo-white.png
  # icon:
    # logo: fontawesome/solid/cloud-bolt
    # repo: fontawesome/brands/github
  favicon: assets/images/bitwyze-arrows-1080x1080.png
  # favicon: assets/images/cloud-bolt.svg
  features:
    - content.code.copy
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - toc.follow
    # - toc.integrate
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline
      primary: indigo
    - scheme: default
      toggle:
        icon: material/toggle-switch
      primary: indigo

extra_css:
  - assets/css/custom.css

# Plugins
plugins:
  - blog
  - search

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mnyethecyberguy
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mnyethecyberguy
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/michaelnye
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/mnyethecyberguy

# Page tree
nav:
  - Home: https://mnye.io/
  - Blog:
    - blog/index.md
  - CLI Cheatsheets:
    - AWS CLI: cli/awscli.md
    - Azure CLI: cli/azcli.md
    - Google Cloud CLI: cli/gcloudcli.md
    - Docker CLI: cli/dockercli.md
    - Git CLI: cli/gitcli.md
  - Resources:
    - References: resources/references.md
    - SANS Cloud Security: https://www.sans.org/cloud-security
    - Secure Service Configuration in AWS, Azure, and GCP Poster: https://www.sans.org/posters/secure-service-configuration-in-aws-azure-gcp/
    - MkDocs Template: resources/mkdocs-template.md
  - AWS: https://aws.amazon.com/
    #- Delete Default Resources: aws/delete-defaults.md
    #- AWS Cloud Workstation: aws/cloud-workstation.md
    #- AWS Console: https://aws.amazon.com/
  - Azure: https://portal.azure.com/
    #- Delete Default Resources: azure/delete-defaults.md
    #- Azure Portal: https://portal.azure.com/
  - GCP: https://cloud.google.com/
    #- Delete Default Resources: gcp/delete-defaults.md
    #- GCP Console: https://cloud.google.com/
  

markdown_extensions: 
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  # - pymdownx.emoji:
      # emoji_index: !!python/name:materialx.emoji.twemoji
      # emoji_generator: !!python/name:materialx.emoji.to_svg
